### ISSUE TITLE
运行异常 ，无法重启

### ISSUE THREAD

**Issue by cqzaiercn** [opq-osc/OPQ#72]
### 事先确认项

- [X] 我确定该反馈是新的，没有和 issue 列表中已有的问题重复
- [X] 我确定查阅过了 官方文档、OPQBot 文档 等所有的信息来源
- [X] 我确定我使用的 QPQBot 是最新版本

### OPQBot 版本

OPQBot_6.9.28

### 系统架构

windows_386

### 错误描述

panic: interface conversion: interface {} is nil, not string [recovered]
        panic: runtime error: slice bounds out of range [-1:]

goroutine 72 [running]:
NetworkFramework.PanicTrace(0x4)
        NetworkFramework@v0.0.0-00010101000000-000000000000/Utils.go:43 +0x24d
main.(*WorkPool).workInit.func1.1()
        QQToy/WorkersPool.go:128 +0x59
panic({0x1559ea0, 0xa839578})
        runtime/panic.go:914 +0x1df
main.(*Sub_0xzFYSE).Sub_0xLWykK(0x1a61dd0, {0x0, 0x0, 0x0})
        QQToy/GitHubMgr.go:60 +0x10e4
main.(*WorkPool).workInit.func1(0x3e)
        QQToy/WorkersPool.go:144 +0x1da
created by main.(*WorkPool).workInit in goroutine 1
        QQToy/WorkersPool.go:125 +0xa1

### 重现步骤

1. 
2. 
3. 
...

**Comment by Strawxg** [comment]
删除opqbot根目录下面的所有文件夹和本体
然后下载最新版本重新登录

**Comment by 949480075** [comment]
下载的是 OPQBot_6.9.28-21358_windows_386 ，win10系统启动只会创建目录，然后就没了，窗口自动关闭。

**Comment by Strawxg** [comment]
> 下载的是 OPQBot_6.9.28-21358_windows_386 ，win10系统启动只会创建目录，然后就没了，窗口自动关闭。

用cmd命令启动. ./OPQBot.exe

**Comment by 949480075** [comment]
> > 下载的是 OPQBot_6.9.28-21358_windows_386 ，win10系统启动只会创建目录，然后就没了，窗口自动关闭。
> 
> 用cmd命令启动. ./OPQBot.exe

效果一样。只创建，不启动。
